CREATE SCHEMA BANK;

USE BANK;

CREATE TABLE BANK.CUSTOMERS
(
    CUSTOMER_NUMBER BIGINT PRIMARY KEY
,   CUSTOMER_NAME VARCHAR(250)
,   CUSTOMER_LAST_NAME VARCHAR(250)
,   CUSTOMER_BIRTHDAY DATE
,   CUSTOMER_GENDER VARCHAR(1)
,   CUSTOMER_ACTIVE BOOLEAN
);

CREATE TABLE BANK.ADDRESS_CUSTOMERS (
    CUSTOMER_NUMBER BIGINT
,   ADRESS_STREET TEXT 
,   ADRESS_NUMBER_EXT INT
,   ADRESS_NUMBER_INT INT
,   ADRESS_CP INT
,   ADRESS_CITY VARCHAR(1000)
,   ADRESS_COUNTRY VARCHAR(1000)
,   ADRESS_ACTUAL BOOLEAN
,   CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUSTOMER_NUMBER) REFERENCES BANK.CUSTOMERS(CUSTOMER_NUMBER)
);

CREATE TABLE BANK.ACCOUNTS(
    CUSTOMER_NUMBER BIGINT
,   ACCOUNT_NUMBER VARCHAR(12) PRIMARY KEY
,   ACCOUNT_TYPE VARCHAR(50)
,   ACCOUNT_NIP VARCHAR(4)
,   ACCOUNT_ACTIVE BOOLEAN 
,   CONSTRAINT FK_ACCOUNTS_CUSTOMER FOREIGN KEY(CUSTOMER_NUMBER) REFERENCES BANK.CUSTOMERS(CUSTOMER_NUMBER)
);

CREATE TABLE BANK.CUSTOMERS_TRANSACTIONS
(
   ACCOUNT_NUMBER VARCHAR(12)
,  TRANSACTION_DATE TIMESTAMP NOT NULL
,  TRANSACTION_DETAIL TEXT
,  TRANSACTION_WITHDRAWAL FLOAT
,  TRANSACTION_DEPOSIT FLOAT
);
